server:
  port: 8084
spring:
  cloud:
    config:
      server:
        git:
          default-label: gateway
          uri: https://github.com/LuisRAnrrango/SWCRE-serverconfig
          search-paths: config-data
application:
  name: config-service
